/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Register with email and password */
    post: operations['registerWithEmail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/verify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm an email address with its 6-digit code */
    post: operations['verifyEmail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/verify/resend': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Resend the verification code (max 1/60s, 5/day) */
    post: operations['resendVerificationCode']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log in with email and password */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Rotate the refresh token and mint a new access token */
    post: operations['refreshSession']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log out of the current session */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/google': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Start the Google OAuth2/PKCE flow */
    get: operations['startGoogleLogin']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/google/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Google OAuth2 callback */
    get: operations['googleLoginCallback']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the authenticated user's profile */
    get: operations['getProfile']
    put?: never
    post?: never
    /** Delete the authenticated user's account and all their data */
    delete: operations['deleteAccount']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/songs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Add a song by file upload or YouTube link (FR-10, FR-11) */
    post: operations['addSong']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/songs/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a song's reference preparation status (FR-14) */
    get: operations['getSong']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/songs/{id}/prepare': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Restart a song's cold path after it failed, without re-uploading (FR-17) */
    post: operations['retrySongPrep']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/analyses': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Put a recording in the analysis queue (FR-22) */
    post: operations['enqueueAnalysis']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/analyses/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get an analysis's current status, scoped to its owner */
    get: operations['getAnalysis']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/analyses/{id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Cancel an analysis while it is queued or waiting_for_reference (FR-25) */
    post: operations['cancelAnalysis']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/analyses/{id}/retry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Restart a failed analysis without re-uploading the recording (FR-26) */
    post: operations['retryAnalysis']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/ws/analyses/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * WebSocket status channel for one analysis (spec 8.3)
     * @description Upgrades to a WebSocket. The client's first message must be `{"token": "<access_token>"}` (never a query parameter, so it never lands in proxy logs); the server then pushes one JSON event per status change, each with a `type` field: `{"type": "queued", "position": N}` while queued; `{"type": "stage", "name": "pitch", "index": 5, "total": 10}` once the E3 worker picks the job up, one push per stage started; `{"type": "done", "analysis_id": "..."}` on success; `{"type": "failed", "error_code": "...", "message": "..."}` on failure (spec 6.8 error codes). `stage`/`done`/`failed` events are relayed from the worker over Redis Pub/Sub (ADR-0010) and are best-effort -- WebSocket is a status-only transport, the final result is always read back over REST (fallback to polling GET /analyses/{id} if the socket drops or an event is missed).
     */
    get: operations['watchAnalysisQueuePosition']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/progress': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get the caller's overall_score points for the progress chart (FR-35)
     * @description Every completed analysis's overall_score, oldest first (spec 7's progress_snapshots, written by the E3 worker once stage 11 succeeds). Not cursor-paginated like a browsable list (spec 8.1): this feeds a chart in one call rather than something a user pages through, so the server caps it at a fixed size instead.
     */
    get: operations['getProgress']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/healthz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness probe */
    get: operations['healthz']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/readyz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness probe (Postgres + Redis reachable) */
    get: operations['readyz']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    RegisterRequest: {
      /** Format: email */
      email: string
      /** @description Rejected if under 10 characters or one of the most common passwords. */
      password: string
      display_name: string
    }
    VerifyRequest: {
      /** Format: email */
      email: string
      code: string
    }
    ResendRequest: {
      /** Format: email */
      email: string
    }
    LoginRequest: {
      /** Format: email */
      email: string
      password: string
    }
    MessageResponse: {
      message: string
    }
    SessionResponse: {
      access_token: string
      expires_in_seconds: number
    }
    User: {
      /** Format: uuid */
      id: string
      /** Format: email */
      email: string
      display_name: string
      email_verified: boolean
      /** Format: date-time */
      created_at: string
    }
    /** @description multipart/form-data. source_type selects the branch: `file` is required and `artist` optional for `upload`; `youtube_url` is required for `youtube` (title then falls back to the video's own title if omitted). */
    AddSongRequest: {
      /** @enum {string} */
      source_type: 'upload' | 'youtube'
      /** @description Required for source_type=upload; optional override for youtube. */
      title?: string
      artist?: string
      /**
       * Format: binary
       * @description Required for source_type=upload. mp3/wav/m4a/flac/ogg, checked by magic bytes.
       */
      file?: string
      /** @description Required for source_type=youtube. Must be a youtube.com/youtu.be link. */
      youtube_url?: string
    }
    Song: {
      /** Format: uuid */
      id: string
      /** @enum {string} */
      source_type: 'upload' | 'youtube'
      title: string
      artist?: string
      duration_sec: number
      /**
       * @description Cold path lifecycle (spec 6.2, 10, FR-14). `ready` means the reference vocal stem and pitch curve are cached and any queued analysis of this song can run immediately.
       * @enum {string}
       */
      prep_status: 'pending' | 'processing' | 'ready' | 'failed'
      /** @description The P-stage currently running (P1-P4, spec 6.4). Absent when not processing. */
      prep_stage?: string
      /** @description Set once prep_status is 'failed' (FR-17); restart via POST /songs/{id}/prepare. */
      prep_error_code?: string
      /** @description False when P3 (Whisper transcription) failed or timed out for this song -- optional stage, never blocks the cold path (FR-18). */
      lyrics_available: boolean
      /**
       * Format: date-time
       * @description When prep_status last reached 'ready'. Absent until then.
       */
      prepared_at?: string
      /** @description True if this submission deduplicated onto an existing song (spec 6.6, FR-13). */
      reused: boolean
      /** Format: date-time */
      created_at: string
    }
    /** @description multipart/form-data. */
    EnqueueAnalysisRequest: {
      /** Format: uuid */
      song_id: string
      /**
       * @description Which analysis mode to run (spec 2.3, FR-27). `clean` (a cappella) is recommended and scores all six aspects at the highest accuracy; `mixed` (any accompaniment) scores four, at reduced accuracy. Defaults to `clean` when omitted.
       * @default clean
       * @enum {string}
       */
      mode: 'clean' | 'mixed'
      /** @description Whether the user may have sung in a different key (FR-31, spec 6.8). Defaults to `false` for `clean` and `true` for `mixed` when omitted. */
      allow_transposition?: boolean
      /**
       * Format: binary
       * @description The user's recording. mp3/wav/m4a/flac/ogg, checked by magic bytes, ≤ MAX_AUDIO_SECONDS.
       */
      recording: string
    }
    Analysis: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      song_id: string
      /**
       * @description waiting_for_reference means the job was created before its song's cold path reached ready; it transitions to queued automatically once the song is ready (spec 6.2, 10.3, FR-16).
       * @enum {string}
       */
      status: 'queued' | 'waiting_for_reference' | 'processing' | 'done' | 'failed' | 'canceled'
      /**
       * @description The mode the user chose at POST /analyses (spec 2.3, FR-27).
       * @enum {string}
       */
      mode: 'clean' | 'mixed'
      /**
       * @description What the worker's stage A3 actually reconciled `mode` to once it saw the recording (spec 6.16) -- e.g. auto-downgraded from `mixed` to `clean` when no accompaniment was detected (FR-29). Absent until that stage completes.
       * @enum {string}
       */
      effective_mode?: 'clean' | 'mixed'
      /** @description 1-based position among currently queued jobs. Absent once no longer queued. */
      queue_position?: number
      /** @description Set by the worker once processing starts. */
      current_stage?: string
      /** @description 1-based position of current_stage among total_stages (spec 6.2), matching the WS `stage` event (spec 8.3). Set once processing starts. */
      current_stage_index?: number
      /** @description Total pipeline stages for this analysis (spec 6.2). */
      total_stages?: number
      /**
       * Format: date-time
       * @description When current_stage began. Lets the client render a live elapsed timer instead of a static label that looks frozen during a multi-minute stage (Demucs/Whisper, spec 6.2).
       */
      current_stage_started_at?: string
      /** @description Every already-completed stage's real recorded duration, keyed by stage name (spec 6.1) -- a running timeline, not just the current stage. */
      stages?: {
        [key: string]: components['schemas']['StageProgress']
      }
      error_code?: string
      pitch_score?: number
      rhythm_score?: number
      vibrato_score?: number
      breath_score?: number
      dynamics_score?: number
      timbre_score?: number
      /** @description Weighted sum of the six aspect scores (spec 6.4), set by stage 11. */
      overall_score?: number
      /** @description Readable per-aspect report with concrete advice (FR-32). */
      feedback_text?: string
      /** @description Which SCORING_WEIGHTS this analysis was scored under (spec 6.4). */
      scoring_version?: string
      /** @description Which named weight profile (`clean_v1`/`mixed_v1`, spec 6.14) overall_score was computed under. Two analyses with different weights_profile must never have their overall_score compared directly without flagging that to the user (FR-49). */
      weights_profile?: string
      /**
       * @description Overall reliability of this analysis's scores (spec 6.15, FR-47). Absent until stage 11 (aggregate) completes.
       * @enum {string}
       */
      confidence?: 'high' | 'medium' | 'low'
      /** @description Per-aspect confidence level, keyed by aspect name (spec 6.15). */
      aspect_confidence?: {
        [key: string]: 'high' | 'medium' | 'low'
      }
      /** @description Machine-readable warning codes (spec 6.18), e.g. `ACCOMPANIMENT_IN_CLEAN_MODE`, `MODE_DOWNGRADED_TO_CLEAN`, `LITTLE_VOICE_DETECTED`, `WEAK_ALIGNMENT`, `KEY_SHIFT_OUT_OF_RANGE`. The client localizes these to a human-readable message rather than showing the code (FR-47). */
      warnings?: string[]
      /** @description Every aspect this mode does not score, mapped to a machine-readable reason (FR-41) -- e.g. `breath`/`timbre` under `NOT_MEASURABLE_WITH_ACCOMPANIMENT` in `mixed`. An aspect listed here is never also present as a `0` in its `*_score` field: it is simply absent there. */
      unavailable_aspects?: {
        [key: string]: string
      }
      /** @description Applied tonality-normalization shift in semitones, if any (spec 6.8, FR-46). Absent when no shift was applied. */
      key_shift_semitones?: number
      piano_roll?: components['schemas']['PianoRoll']
      /** Format: date-time */
      created_at: string
      /**
       * Format: date-time
       * @description When the *current* queued/waiting_for_reference wait began. Equal to created_at for a fresh submission; reset to the retry time by POST /analyses/{id}/retry (FR-26), so a client's live wait timer never measures from a stale original submission.
       */
      queued_at: string
      /** Format: date-time */
      completed_at?: string
    }
    /** @description Display-only summary of one completed pipeline stage (spec 6.1) -- never the stage's own `data` (which can carry a full pitch curve for the "pitch" stage, already exposed separately as pitch_curve_json) or its error detail. */
    StageProgress: {
      /** @enum {string} */
      status: 'done' | 'failed'
      /** @description Real wall-clock time the stage took. */
      duration_ms: number
    }
    /** @description FR-31 overlay data: the user's pitch curve and the reference curve already resampled onto the user's own time grid, frame for frame, so the client never needs to redo the DTW alignment (spec 6.3.4/6.3.5) to draw the two curves together. */
    PianoRoll: {
      /** @description Seconds between consecutive frames; frame i's time is i * hop_seconds. */
      hop_seconds: number
      user_hz: (number | null)[]
      reference_hz: (number | null)[]
      /** @description Signed cents deviation per frame, null wherever either side is unvoiced. */
      deviation_cents: (number | null)[]
      /** @description deviation_cents already thresholded against PIANO_ROLL_OFF_PITCH_CENTS. */
      off_pitch: boolean[]
    }
    /** @description One dated overall_score sample for the FR-35/FR-49 progress chart. mode/confidence are denormalized alongside overall_score: two points with different mode were scored under different weights_profile (spec 6.14) and must be visually distinguished, never presented as directly comparable (FR-49). */
    ProgressPoint: {
      /** Format: uuid */
      analysis_id: string
      overall_score: number
      /** @enum {string} */
      mode: 'clean' | 'mixed'
      /** @enum {string} */
      confidence?: 'high' | 'medium' | 'low'
      /** Format: date-time */
      created_at: string
    }
    /** @description RFC 9457 application/problem+json body. */
    Problem: {
      type: string
      title: string
      status: number
      detail: string
      /** @description Stable machine-readable error code; frontend localizes on this. */
      code: string
      request_id: string
    }
  }
  responses: {
    /** @description The request failed validation. */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['Problem']
      }
    }
    /** @description Missing or invalid access token. */
    Unauthorized: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['Problem']
      }
    }
    /** @description Rate limit or lockout in effect. */
    TooManyRequests: {
      headers: {
        'Retry-After'?: number
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['Problem']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  registerWithEmail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest']
      }
    }
    responses: {
      /** @description Accepted. The response never reveals whether the email was already registered (spec 9.1). */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  verifyEmail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyRequest']
      }
    }
    responses: {
      /** @description Email verified. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
      /** @description Code invalid or expired. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  resendVerificationCode: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResendRequest']
      }
    }
    responses: {
      /** @description Sent, if the account exists and is unverified. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Authenticated. Sets the refresh token as an httpOnly cookie scoped to /api/v1/auth; the response body carries only the access token. */
      200: {
        headers: {
          'Set-Cookie'?: string
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionResponse']
        }
      }
      /** @description Invalid credentials, or correct password but email not verified. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  refreshSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description New access token issued; refresh cookie rotated. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionResponse']
        }
      }
      /** @description Refresh token missing, expired, or reused (forces re-login). */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logged out; refresh cookie cleared. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
    }
  }
  startGoogleLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Redirect to Google's consent screen. */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  googleLoginCallback: {
    parameters: {
      query: {
        code: string
        state: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Redirect to APP_BASE_URL with the refresh cookie set. The access token is never placed in the URL; the frontend calls /auth/refresh on load to mint its first one. */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description OAuth state mismatch or missing PKCE cookies. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  getProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The caller's profile. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  deleteAccount: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Account and every session revoked; cascades to owned data. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
    }
  }
  addSong: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['AddSongRequest']
      }
    }
    responses: {
      /** @description Song catalogued and its cold path (reference separation, transcription, pitch curve) queued immediately (spec 6.2, FR-15) -- poll GET /songs/{id} or watch prep_status for readiness. `reused: true` means an identical song (by content hash / YouTube video id) already existed, this upload was deduplicated (spec 6.6, FR-13), and no new cold path run was queued. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Song']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      /** @description YouTube import is disabled (spec 11.4). */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Audio exceeds MAX_UPLOAD_MB. */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  getSong: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The song. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Song']
        }
      }
      401: components['responses']['Unauthorized']
      /** @description No song with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  retrySongPrep: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Re-queued onto songs:prep. Progress follows via GET /songs/{id} (FR-14). */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Song']
        }
      }
      401: components['responses']['Unauthorized']
      /** @description No song with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description The song's prep_status is not 'failed' (`SONG_PREP_NOT_FAILED`). */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  enqueueAnalysis: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['EnqueueAnalysisRequest']
      }
    }
    responses: {
      /** @description Queued, or waiting_for_reference if the song's cold path hasn't reached ready yet (spec 6.2, 10.3, FR-16) -- it transitions to queued automatically, no re-submission needed. Position updates follow over the WebSocket channel. */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Analysis']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      /** @description No song with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description The song's cold path already failed (`REFERENCE_PREP_FAILED`, FR-17). */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Recording exceeds MAX_UPLOAD_MB. */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  getAnalysis: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The analysis. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Analysis']
        }
      }
      401: components['responses']['Unauthorized']
      /** @description No analysis with this id owned by the caller. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  cancelAnalysis: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Canceled. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Analysis']
        }
      }
      401: components['responses']['Unauthorized']
      /** @description No analysis with this id owned by the caller. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description The analysis is not queued or waiting_for_reference anymore (`ANALYSIS_NOT_QUEUED`). */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  retryAnalysis: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Re-queued, or back to waiting_for_reference if the song's cold path still hasn't reached ready (spec 6.2, 10.3, FR-16) -- same duality as enqueueAnalysis. Position updates follow over the WebSocket channel. */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Analysis']
        }
      }
      401: components['responses']['Unauthorized']
      /** @description No analysis with this id owned by the caller. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Either the analysis is not in the failed state (`ANALYSIS_NOT_FAILED`), or its song's cold path itself failed (`REFERENCE_PREP_FAILED`, FR-17) -- restart the song's prep (POST /songs/{id}/prepare) before retrying this analysis again. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  watchAnalysisQueuePosition: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Switching Protocols to WebSocket. */
      101: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
    }
  }
  getProgress: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The caller's progress points. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProgressPoint'][]
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  healthz: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Process is up. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  readyz: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Ready to serve traffic. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description A dependency is unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
