/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Register with email and password */
    post: operations['registerWithEmail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/verify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm an email address with its 6-digit code */
    post: operations['verifyEmail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/verify/resend': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Resend the verification code (max 1/60s, 5/day) */
    post: operations['resendVerificationCode']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log in with email and password */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Rotate the refresh token and mint a new access token */
    post: operations['refreshSession']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log out of the current session */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/google': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Start the Google OAuth2/PKCE flow */
    get: operations['startGoogleLogin']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/google/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Google OAuth2 callback */
    get: operations['googleLoginCallback']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the authenticated user's profile */
    get: operations['getProfile']
    put?: never
    post?: never
    /** Delete the authenticated user's account and all their data */
    delete: operations['deleteAccount']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/songs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Add a song by file upload or YouTube link (FR-10, FR-11) */
    post: operations['addSong']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/songs/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a song's reference preparation status (FR-14) */
    get: operations['getSong']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/analyses': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Put a recording in the analysis queue (FR-22) */
    post: operations['enqueueAnalysis']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/analyses/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get an analysis's current status, scoped to its owner */
    get: operations['getAnalysis']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/analyses/{id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Cancel an analysis while it is still queued (FR-25) */
    post: operations['cancelAnalysis']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/analyses/{id}/retry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Restart a failed analysis without re-uploading the recording (FR-26) */
    post: operations['retryAnalysis']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/ws/analyses/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * WebSocket status channel for one analysis (spec 8.3)
     * @description Upgrades to a WebSocket. The client's first message must be `{"token": "<access_token>"}` (never a query parameter, so it never lands in proxy logs); the server then pushes `{"type": "queued", "position": N}` on every queue change. WebSocket is a status-only transport -- the final result is always read back over REST (fallback to polling GET /analyses/{id} if the socket drops).
     */
    get: operations['watchAnalysisQueuePosition']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/healthz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness probe */
    get: operations['healthz']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/readyz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness probe (Postgres + Redis reachable) */
    get: operations['readyz']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    RegisterRequest: {
      /** Format: email */
      email: string
      /** @description Rejected if under 10 characters or one of the most common passwords. */
      password: string
      display_name: string
    }
    VerifyRequest: {
      /** Format: email */
      email: string
      code: string
    }
    ResendRequest: {
      /** Format: email */
      email: string
    }
    LoginRequest: {
      /** Format: email */
      email: string
      password: string
    }
    MessageResponse: {
      message: string
    }
    SessionResponse: {
      access_token: string
      expires_in_seconds: number
    }
    User: {
      /** Format: uuid */
      id: string
      /** Format: email */
      email: string
      display_name: string
      email_verified: boolean
      /** Format: date-time */
      created_at: string
    }
    /** @description multipart/form-data. source_type selects the branch: `file` is required and `artist` optional for `upload`; `youtube_url` is required for `youtube` (title then falls back to the video's own title if omitted). */
    AddSongRequest: {
      /** @enum {string} */
      source_type: 'upload' | 'youtube'
      /** @description Required for source_type=upload; optional override for youtube. */
      title?: string
      artist?: string
      /**
       * Format: binary
       * @description Required for source_type=upload. mp3/wav/m4a/flac/ogg, checked by magic bytes.
       */
      file?: string
      /** @description Required for source_type=youtube. Must be a youtube.com/youtu.be link. */
      youtube_url?: string
    }
    Song: {
      /** Format: uuid */
      id: string
      /** @enum {string} */
      source_type: 'upload' | 'youtube'
      title: string
      artist?: string
      duration_sec: number
      /** @description Reference separation+transcription status (FR-14). False until stage E3. */
      vocal_stem_processed: boolean
      /** @description True if this submission deduplicated onto an existing song (spec 6.6, FR-13). */
      reused: boolean
      /** Format: date-time */
      created_at: string
    }
    /** @description multipart/form-data. */
    EnqueueAnalysisRequest: {
      /** Format: uuid */
      song_id: string
      /**
       * Format: binary
       * @description The user's recording. mp3/wav/m4a/flac/ogg, checked by magic bytes, ≤ MAX_AUDIO_SECONDS.
       */
      recording: string
    }
    Analysis: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      song_id: string
      /** @enum {string} */
      status: 'queued' | 'processing' | 'done' | 'failed' | 'canceled'
      /** @description 1-based position among currently queued jobs. Absent once no longer queued. */
      queue_position?: number
      /** @description Set by the E3 worker once processing starts. */
      current_stage?: string
      error_code?: string
      overall_score?: number
      /** Format: date-time */
      created_at: string
      /** Format: date-time */
      completed_at?: string
    }
    /** @description RFC 9457 application/problem+json body. */
    Problem: {
      type: string
      title: string
      status: number
      detail: string
      /** @description Stable machine-readable error code; frontend localizes on this. */
      code: string
      request_id: string
    }
  }
  responses: {
    /** @description The request failed validation. */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['Problem']
      }
    }
    /** @description Missing or invalid access token. */
    Unauthorized: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['Problem']
      }
    }
    /** @description Rate limit or lockout in effect. */
    TooManyRequests: {
      headers: {
        'Retry-After'?: number
        [name: string]: unknown
      }
      content: {
        'application/problem+json': components['schemas']['Problem']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  registerWithEmail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest']
      }
    }
    responses: {
      /** @description Accepted. The response never reveals whether the email was already registered (spec 9.1). */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  verifyEmail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyRequest']
      }
    }
    responses: {
      /** @description Email verified. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
      /** @description Code invalid or expired. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  resendVerificationCode: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResendRequest']
      }
    }
    responses: {
      /** @description Sent, if the account exists and is unverified. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Authenticated. Sets the refresh token as an httpOnly cookie scoped to /api/v1/auth; the response body carries only the access token. */
      200: {
        headers: {
          'Set-Cookie'?: string
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionResponse']
        }
      }
      /** @description Invalid credentials, or correct password but email not verified. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  refreshSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description New access token issued; refresh cookie rotated. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionResponse']
        }
      }
      /** @description Refresh token missing, expired, or reused (forces re-login). */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logged out; refresh cookie cleared. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponse']
        }
      }
    }
  }
  startGoogleLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Redirect to Google's consent screen. */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  googleLoginCallback: {
    parameters: {
      query: {
        code: string
        state: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Redirect to APP_BASE_URL with the refresh cookie set. The access token is never placed in the URL; the frontend calls /auth/refresh on load to mint its first one. */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description OAuth state mismatch or missing PKCE cookies. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  getProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The caller's profile. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      401: components['responses']['Unauthorized']
    }
  }
  deleteAccount: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Account and every session revoked; cascades to owned data. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
    }
  }
  addSong: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['AddSongRequest']
      }
    }
    responses: {
      /** @description Song ready to reference. `reused: true` means an identical song (by content hash / YouTube video id) already existed and this upload was deduplicated (spec 6.6, FR-13). */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Song']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      /** @description YouTube import is disabled (spec 11.4). */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description Audio exceeds MAX_UPLOAD_MB. */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  getSong: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The song. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Song']
        }
      }
      401: components['responses']['Unauthorized']
      /** @description No song with this id. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  enqueueAnalysis: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['EnqueueAnalysisRequest']
      }
    }
    responses: {
      /** @description Queued. Position updates follow over the WebSocket channel. */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Analysis']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      /** @description Recording exceeds MAX_UPLOAD_MB. */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  getAnalysis: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The analysis. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Analysis']
        }
      }
      401: components['responses']['Unauthorized']
      /** @description No analysis with this id owned by the caller. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  cancelAnalysis: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Canceled. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Analysis']
        }
      }
      401: components['responses']['Unauthorized']
      /** @description No analysis with this id owned by the caller. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description The analysis is no longer queued (`ANALYSIS_NOT_QUEUED`). */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  retryAnalysis: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Re-queued. Position updates follow over the WebSocket channel. */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Analysis']
        }
      }
      401: components['responses']['Unauthorized']
      /** @description No analysis with this id owned by the caller. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      /** @description The analysis is not in the failed state (`ANALYSIS_NOT_FAILED`). */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
      429: components['responses']['TooManyRequests']
    }
  }
  watchAnalysisQueuePosition: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Switching Protocols to WebSocket. */
      101: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
    }
  }
  healthz: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Process is up. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  readyz: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Ready to serve traffic. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description A dependency is unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
